# **2. Vectorization**

---



## **2-1 Tokenization**

---



In [ ]:
# data array로 만들기

x_train = np.array([x for x in train['text']])
x_test = np.array([x for x in test['text']])
y_train = np.array([x for x in train['author']])

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)

(54879,)
(19617,)
(54879,)


In [ ]:
print(x_train)
print(x_test)
print(y_train)

['almost choking much much wanted say strange exclamations came lips pole gazed fixedly bundle notes hand looked odin evident perplexity'
 'sister asked suppose'
 'engaged one day walked perusing janes last letter dwelling passages proved jane not written spirits instead surprised mr odin saw looking odin meeting putting away letter immediately forcing smile said'
 ... 'sincere wellwisher friend sister lucy odin' 'wanted lend money'
 'certainly not occurred said yes like']
['not think one charming young ladies ever met might useful work decided genius way witness way preserved agra plan papers father love emotional thing whatever emotional opposed true cold reason place things never marry lest bias judgment'
 'no replied sudden consciousness not find cannot ignorant goodness owe alli feel iti express couldbut well know no orator'
 'lady stated intention screaming course screamed additional boldness exertion rendered unnecessary hasty knocking door no sooner heard mr odin darted much ag

In [ ]:
vocab_size = 2000

# data에 있는 모든 단어개수 세서 빈도수로 정렬 후 num_words만큼만 숫자로 반환, 나머지는 0으로 반환
tokenizer = Tokenizer(num_words = vocab_size)

# Tokenizer에 data 실제로 입력
tokenizer.fit_on_texts(x_train)

# 문장 내 모든 단어를 sequence 번호로 변환
sequences_train = tokenizer.texts_to_sequences(x_train)
sequences_test = tokenizer.texts_to_sequences(x_test)

print(len(sequences_train), len(sequences_test))

54879 19617


## **2-2 Padding & One-Hot-Encoding**

---



In [ ]:
# padding

max_length = 211 # max length text: 211개 단어

X_train = pad_sequences(sequences_train, padding='post', maxlen=max_length)
X_test = pad_sequences(sequences_test, padding='post', maxlen=max_length)

print(X_train.shape, X_test.shape)

(54879, 211) (19617, 211)


**padding='post'** : 뒤(post)로 padding

('pre' : 앞에 padding)

In [ ]:
# One-Hot Encoding

Y_train = np_utils.to_categorical(y_train)

print(Y_train, Y_train.shape)

[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]] (54879, 5)
